Tm/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.testing,name='tm-index'),
    path('get_tasks/',views.get_deadline_tasks,name='get-tasks'),
    path('get_daily_tasks/<int:id>',views.get_daily_tasks,name='daily-tasks'),
    path('post-daily-tasks/',views.post_daily_task,name='post-daily'),
    path('post-targeted-tasks/',views.post_target_task,name='post-target'),
    path('put-targeted-tasks/<int:id>',views.put_target_task,name='put-target'),
    path('put-daily-tasks/<int:id>',views.put_daily_task,name='put-daily'),
    path('delete-target-tasks/<int:id>',views.delete_target_task,name='delete-target'),
    path('remaining-tasks/',views.count_tasks,name='count-tasks'),
    path('delete-daily-tasks/<int:id>',views.delete_daily_tasks,name='delete-daily-tasks')
]

main/urls.py
from django.urls import path
from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
    path('login/',views.login_page,name='login'),
    path('logout/',views.logout,name='logout'),
    path('api-auth-token/',views.get_user_token,name='auth_token')
]

protes/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('journal/', include('journal.urls')),
    path('sign-up/', include('sign_up.urls')),
    path('bookmarks/', include('bookmarkmanager.urls')),
    path('recipe-manager/', include('recipe_manager.urls')),
    path('task-manager/',include('Tm.urls')),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link
  href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
  rel="stylesheet"
  integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
  crossorigin="anonymous"
  >
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">

  {% block meta %}
  {% endblock meta %}
</head>

<body>
  <nav class="navbar navbar-expand-lg navbar-light bg-light custom-nav">
    <a class="navbar-brand" href="/">Navbar</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    {% if user.is_authenticated %}
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item active">
          <a class="nav-link" href="/task-manager">Tasks <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/recipe-manager">Recipes</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/bookmarks">Bookmarks</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Motivation</a>
        </li>
      </ul>
    </div>
    <a href="{% url 'main:logout' %}" type="button" class="btn btn-danger d-flex">Logout</a>
    {% endif %}
  </nav>


  {% block content %}
  {% endblock content %}

<footer class="bg-dark text-center text-white">
  <!-- Grid container -->
  <div class="container p-4 pb-0">
    <!-- Section: Social media -->
    <section class="mb-4">
      <!-- Facebook -->
      <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button"
        ><i class="fab fa-facebook-f"></i
      ></a>

      <!-- Twitter -->
      <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button"
        ><i class="fab fa-twitter"></i
      ></a>

      <!-- Google -->
      <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button"
        ><i class="fab fa-google"></i
      ></a>

      <!-- Instagram -->
      <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button"
        ><i class="fab fa-instagram"></i
      ></a>

      <!-- Linkedin -->
      <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button"
        ><i class="fab fa-linkedin-in"></i
      ></a>

      <!-- Github -->
      <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button"
        ><i class="fab fa-github"></i
      ></a>
    </section>
    <!-- Section: Social media -->
  </div>
  <!-- Grid container -->

  <!-- Copyright -->
  <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2);">
    Made by Protes team
  </div>
  <!-- Copyright -->
</footer>

</body>
</html>