Tm/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.testing,name='tm-index'),
    path('get_tasks/',views.get_deadline_tasks,name='get-tasks'),
    path('get_daily_tasks/<int:id>',views.get_daily_tasks,name='daily-tasks'),
    path('post-daily-tasks/',views.post_daily_task,name='post-daily'),
    path('post-targeted-tasks/',views.post_target_task,name='post-target'),
    path('put-targeted-tasks/<int:id>',views.put_target_task,name='put-target'),
    path('put-daily-tasks/<int:id>',views.put_daily_task,name='put-daily'),
    path('delete-target-tasks/<int:id>',views.delete_target_task,name='delete-target'),
    path('remaining-tasks/',views.count_tasks,name='count-tasks'),
    path('delete-daily-tasks/<int:id>',views.delete_daily_tasks,name='delete-daily-tasks')
]

main/urls.py
from django.urls import path
from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
    path('login/',views.login_page,name='login'),
    path('logout/',views.logout,name='logout'),
    path('api-auth-token/',views.get_user_token,name='auth_token')
]

protes/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('journal/', include('journal.urls')),
    path('sign-up/', include('sign_up.urls')),
    path('bookmarks/', include('bookmarkmanager.urls')),
    path('recipe-manager/', include('recipe_manager.urls')),
    path('task-manager/',include('Tm.urls')),
]

main/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.translation import ugettext_lazy as _
from django.db.models.signals import post_save
from django.dispatch import receiver
import binascii
import os

# Create your models here.

class UserToken(models.Model):
    key = models.CharField(max_length=40,primary_key=True)
    user =  models.OneToOneField(
        User,related_name='auth_token',
        on_delete= models.CASCADE,
        verbose_name=("User")
    )
    created = models.DateTimeField(_("Created"),auto_now_add=True)

    class Meta:
        verbose_name = _("Token")
        verbose_name_plural = _("Tokens")
    
    def save(self,*args, **kwargs):
        if not self.key:
            self.key = self.generate_key()
        return super(UserToken,self).save(*args, **kwargs)

    def generate_key(self):
        return binascii.hexlify(os.urandom(20)).decode()
    
    @receiver(post_save, sender=User)
    def create_user_usertoken(sender, instance, created, **kwargs):
        if created:
            UserToken.objects.create(user=instance)

    @receiver(post_save, sender=User)
    def save_user_usertoken(sender, instance, **kwargs):
        instance.auth_token.save()

    def __str__(self):
        return self.key

main/views.py
from django.urls import reverse
from .models import UserToken
from django.http.response import JsonResponse
from django.shortcuts import redirect, render
from django.contrib.auth import authenticate,login
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth import logout as django_logout

def home(request):
    if request.user.is_authenticated:
        return redirect('tm-index')        
    return render(request, 'main/home.html')

@csrf_exempt
def login_page(request):
    if request.user.is_authenticated:
        return redirect('tm-index')      

    response = {}
    if request.method == "POST":
        username = request.POST.get("username")
        password = request.POST.get("password")
        user = authenticate(username=username,password=password)

        if user is not None:
            if not hasattr(user,'auth_token'):
                UserToken.objects.create(user=user)
            auth_token = user.auth_token
            login(request,user)
            response['auth_token'] = auth_token.key
            return redirect('tm-index')
        
        response['error'] = True
        return render(request,'main/login.html' ,response,status=400)

    return render(request,'main/login.html')

@csrf_exempt
def get_user_token(request):
    response = {}
    username = request.POST.get("username")
    password = request.POST.get("password")
    user = authenticate(username=username,password=password)
    if user is not None:
        if not hasattr(user,'auth_token'):
            UserToken.objects.create(user=user)
        auth_token = user.auth_token
        response['auth_token'] = auth_token.key
        return JsonResponse(response,content_type='application/json',status=200)
        
    response['error'] = f"{username} : {password}"
    return JsonResponse(response,content_type='application/json',status=400)

def logout(request):
    django_logout(request)
    return redirect('main:home')

main/templates/main/home.html
{% extends 'base.html' %} {% load static %} {% block meta %}
<title>Homepage</title>

{% endblock meta %} {% block content %}
<div
  class="
    container
    d-flex
    flex-column
    justify-content-center
    align-items-center
    slide-in
  "
  style="color: white; width: 50%; height: 100vh"
>
  <h1 style="font-size: 60px; text-align: center" class="testing">
    <strong>A place where you can keep up with your productivity</strong>
  </h1>
  <div
    class="button-container container d-flex justify-content-center"
    style="box-sizing: border-box"
  >
    <button id="log-in" type="button" class="btn btn-light">Log In</button>
    <button id="sign-up" type="button" class="btn btn-dark">Sign Up</button>
  </div>
</div>

<div
  class="container d-flex flex-column align-items-center"
  style="color: white; margin-bottom: 5em"
>
  <h1 style="margin-bottom: 1em">Made By:</h1>
  <div class="grid-displays">
    <div style="text-align: center">
      <img
        style="
          border-radius: 50%;
          width: 150px;
          height: 150px;
          object-fit: cover;
        "
        src="{% static 'img/fatyooshi.jpg' %}"
      />
      <p>Ikramullah</p>
    </div>
    <div style="text-align: center">
      <img
        style="
          border-radius: 50%;
          width: 150px;
          height: 150px;
          object-fit: cover;
        "
        src="{% static 'img/serima.jpeg' %}"
      />
      <p>Serima Nuranisa</p>
    </div>
    <div style="text-align: center">
      <img
        style="
          border-radius: 50%;
          width: 150px;
          height: 150px;
          object-fit: cover;
        "
      />
      <p>Naufal</p>
    </div>
    <div style="text-align: center">
      <img
        style="
          border-radius: 50%;
          width: 150px;
          height: 150px;
          object-fit: cover;
        "
      />
      <p>Figo Athallah</p>
    </div>
    <div style="text-align: center">
      <img
        style="
          border-radius: 50%;
          width: 150px;
          height: 150px;
          object-fit: cover;
        "
      />
      <p>Imam Chaidar</p>
    </div>
    <div style="text-align: center">
      <img
        style="
          border-radius: 50%;
          width: 150px;
          height: 150px;
          object-fit: cover;
        "
      />
      <p>Fariz</p>
    </div>
  </div>
</div>

<style>
  @keyframes slide-in {
    from {
      opacity: 0;
    }
    to {
      opacity: 1;
    }
  }

  .slide-in {
    animation: slide-in 1000ms;
    animation-timing-function: ease-in-out;
  }

  .grid-displays {
    display: grid;
    grid-template-columns: repeat(3, 1fr);
    column-gap: 2em;
    row-gap: 2em;
  }

  .button-container button {
    padding: 1em !important;
    margin-top: 3em;
    margin-right: 1em;
  }

  @media only screen and (max-width: 768px) {
    .testing {
      font-size: 30px !important;
    }
    .container {
      width: 90% !important;
    }

    .button-container {
      width: 100% !important;
    }

    .grid-displays {
      column-gap: 0.7em;
      row-gap: 0.7em;
    }

    img {
      width: 80px !important;
      height: 80px !important;
    }
  }
</style>

<script type="text/javascript">
  document.getElementById("sign-up").onclick = function () {
    location.href = "/sign-up";
  };
  document.getElementById("log-in").onclick = function () {
    location.href = "/login";
  };
</script>

{% endblock content %}

main/templates/main/login.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
{% endblock meta %}
<title>Login</title>
{% block content %}
    <div
     class="container 
            d-flex 
            justify-content-center 
            align-items-center 
            flex-column"
    style = "
    background-color: white; 
    border-radius: 10px;
    max-width: 450px;
    min-height: 400px;
    margin-bottom: 4em;
    "        
    >
        <h1>Login</h1> 
        <form action="{% url 'main:login' %}" method="post">
            <div class="form-group">
              <label for="exampleInputEmail1">Username</label>
              <input type="text" name="username" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Enter email">
              <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
            </div>
            <div class="form-group" style="margin-bottom: 1em;">
              <label for="exampleInputPassword1" name="password">Password</label>
              <input type="password" class="form-control" name="password" id="exampleInputPassword1" placeholder="Password">
            </div>
            <button type="submit" class="btn btn-primary">Submit</button>
          </form>
    </div>
{% endblock content %}